version: '3'

services:
  upload:
    container_name: rest-api-node16
    image: node:16
    working_dir: /usr/src/app
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./dist/:/usr/src/app/dist/
    ports:
      - "3333:3333"
